from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, -2, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 255, 255);")
        self.label_result.setObjectName("label_result")
        self.Button0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button0.setGeometry(QtCore.QRect(0, 312, 150, 90))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button0.setFont(font)
        self.Button0.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button0.setObjectName("Button0")
        self.Button_ravn = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ravn.setGeometry(QtCore.QRect(150, 312, 150, 90))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ravn.setFont(font)
        self.Button_ravn.setStyleSheet("background-color: rgb(58, 117, 255);\n"
"color: rgb(255, 255, 255);")
        self.Button_ravn.setObjectName("Button_ravn")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(0, 231, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(100, 231, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button2.setObjectName("Button2")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(200, 231, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button3.setObjectName("Button3")
        self.Button6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button6.setGeometry(QtCore.QRect(199, 150, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button6.setFont(font)
        self.Button6.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button6.setObjectName("Button6")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(0, 150, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button4.setFont(font)
        self.Button4.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button4.setObjectName("Button4")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(100, 150, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button5.setFont(font)
        self.Button5.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button5.setObjectName("Button5")
        self.Button9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button9.setGeometry(QtCore.QRect(200, 69, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button9.setFont(font)
        self.Button9.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button9.setObjectName("Button9")
        self.Button7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button7.setGeometry(QtCore.QRect(0, 69, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button7.setFont(font)
        self.Button7.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button7.setObjectName("Button7")
        self.Button8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button8.setGeometry(QtCore.QRect(100, 69, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button8.setFont(font)
        self.Button8.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button8.setObjectName("Button8")
        self.Button_umn = QtWidgets.QPushButton(self.centralwidget)
        self.Button_umn.setGeometry(QtCore.QRect(300, 69, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_umn.setFont(font)
        self.Button_umn.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button_umn.setObjectName("Button_umn")
        self.Button_del = QtWidgets.QPushButton(self.centralwidget)
        self.Button_del.setGeometry(QtCore.QRect(300, 150, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_del.setFont(font)
        self.Button_del.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button_del.setObjectName("Button_del")
        self.Button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.Button_minus.setGeometry(QtCore.QRect(300, 231, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_minus.setFont(font)
        self.Button_minus.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button_minus.setObjectName("Button_minus")
        self.Button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.Button_plus.setGeometry(QtCore.QRect(300, 312, 71, 90))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_plus.setFont(font)
        self.Button_plus.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.Button_plus.setObjectName("Button_plus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_function()
        self.is_ravn=False
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.Button_ravn.setText(_translate("MainWindow", "="))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Button_umn.setText(_translate("MainWindow", "*"))
        self.Button_del.setText(_translate("MainWindow", "/"))
        self.Button_minus.setText(_translate("MainWindow", "-"))
        self.Button_plus.setText(_translate("MainWindow", "+"))

    def add_function(self):
        self.Button0.clicked.connect(lambda:self.write_number(self.Button0.text()))
        self.Button1.clicked.connect(lambda: self.write_number(self.Button1.text()))
        self.Button2.clicked.connect(lambda: self.write_number(self.Button2.text()))
        self.Button3.clicked.connect(lambda: self.write_number(self.Button3.text()))
        self.Button4.clicked.connect(lambda: self.write_number(self.Button4.text()))
        self.Button5.clicked.connect(lambda: self.write_number(self.Button5.text()))
        self.Button6.clicked.connect(lambda: self.write_number(self.Button6.text()))
        self.Button7.clicked.connect(lambda: self.write_number(self.Button7.text()))
        self.Button8.clicked.connect(lambda: self.write_number(self.Button8.text()))
        self.Button9.clicked.connect(lambda: self.write_number(self.Button9.text()))
        self.Button_del.clicked.connect(lambda: self.write_number(self.Button_del.text()))
        self.Button_umn.clicked.connect(lambda: self.write_number(self.Button_umn.text()))
        self.Button_plus.clicked.connect(lambda: self.write_number(self.Button_plus.text()))
        self.Button_minus.clicked.connect(lambda: self.write_number(self.Button_minus.text()))

        self.Button_ravn.clicked.connect(self.result)
    def result(self):
        res=eval(self.label_result.text())
        self.label_result.setText("Результат: "+str(res))
        self.is_ravn=True
    def write_number(self,number):
        if (self.label_result.text()=="0" or self.is_ravn):
            self.label_result.setText(number)
            self.is_ravn=False
        else:
            self.label_result.setText(self.label_result.text()+number)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
